version: '2'
services:
  mariadb:
    image: 'mariadb:10.4'
    working_dir: /application
    environment:
      - MYSQL_ROOT_PASSWORD=magento_root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento_user
      - MYSQL_PASSWORD=magento_password
    ports:
      - '25003:3306'
    volumes:
      - mariadb_data:/var/lib/mysql
  elasticsearch:
    image: elasticsearch:7.17.4
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - 'elasticsearch_data:/usr/share/elasticsearch/data'
  test:
    image: php:7.4-apache
    ports:
      - '8080:80'
  magento:
    build:
      context: ./magento
    ports:
      - 8080:80
    depends_on:
      - mariadb
      - elasticsearch
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
  elasticsearch_data:
    driver: local
