version: '2'
services:
  mariadb:
    image: 'mariadb:10.4'
    working_dir: /application
    environment:
      - MYSQL_ROOT_PASSWORD=magento_root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento_user
      - MYSQL_PASSWORD=magento_password
    ports:
      - '25003:3306'
    volumes:
      - mariadb_data:/var/lib/mysql
  # magento:
  #   image: docker.io/bitnami/magento:latest
  #   ports:
  #     - '80:8080'
  #     - '443:8443'
  #   environment:
  #     - MAGENTO_HOST=localhost
  #     - MAGENTO_DATABASE_HOST=mariadb
  #     - MAGENTO_DATABASE_PORT_NUMBER=3306
  #     - MAGENTO_DATABASE_USER=bn_magento
  #     - MAGENTO_DATABASE_NAME=bitnami_magento
  #     - ELASTICSEARCH_HOST=elasticsearch
  #     - ELASTICSEARCH_PORT_NUMBER=9200
  #     # ALLOW_EMPTY_PASSWORD is recommended only for development.
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   volumes:
  #     - 'magento_data:/bitnami/magento'
  #   depends_on:
  #     - mariadb
  #     - elasticsearch
  elasticsearch:
    image: elasticsearch:7.17.4
    environment:
      - discovery.type=single-node
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
  test:
    image: php:7.4-apache
    ports:
      - '8080:80'
  magento:
    build:
      context: ./magento
    ports:
      - 8080:80
    depends_on:
      - mariadb
      - elasticsearch
volumes:
  mariadb_data:
    driver: local
  magento_data:
    driver: local
  elasticsearch_data:
    driver: local
